### ISSUE TITLE
tailon version 1.4.3 (Installed via pip3 install tailon)

### ISSUE THREAD

**Issue by subvhome** [gvalkov/tailon#53]
Seems to be working fine... the console is spitting out:

```
[+24464.636087][ERROR] WebSocket
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sockjs/tornado/transports/websocket.py", line 63, in on_message
    self.session.on_messages(msg)
  File "/usr/local/lib/python3.6/site-packages/sockjs/tornado/session.py", line 419, in on_messages
    self.conn.on_message(msg)
  File "/usr/local/lib/python3.6/site-packages/tailon/server.py", line 162, in on_message
    command = escape.json_decode(message)
  File "/usr/local/lib64/python3.6/site-packages/tornado/escape.py", line 87, in json_decode
    return json.loads(to_basestring(value))
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Running CentOS 8
python3

**Comment by subvhome** [comment]
Turned out a client was connected and had some cached settings in their browser. Closing the tab resolved.
