### ISSUE TITLE
Not compatible with Python 3.10

### ISSUE THREAD

**Issue by titus-kruse** [gvalkov/tailon#62]
Just installed Python 3 on Ubuntu Linux 22. Installed Tailon with pip and tried to tail syslog:

$ pip install tailon

$ tailon -f /var/log/syslog
Traceback (most recent call last):
  File "/usr/local/bin/tailon", line 5, in <module>
    from tailon.main import main
  File "/usr/local/lib/python3.10/dist-packages/tailon/main.py", line 16, in <module>
    from tornado import ioloop, httpserver
  File "/usr/local/lib/python3.10/dist-packages/tornado/httpserver.py", line 34, in <module>
    from tornado.http1connection import HTTP1ServerConnection, HTTP1ConnectionParameters
  File "/usr/local/lib/python3.10/dist-packages/tornado/http1connection.py", line 29, in <module>
    from tornado import httputil
  File "/usr/local/lib/python3.10/dist-packages/tornado/httputil.py", line 106, in <module>
    class HTTPHeaders(collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'

Any idea to work around this issue?

**Comment by FxProgrm** [comment]
Hi Titus,
If you haven't resolved it, you should be able to enable the following to get the missing attribute.
https://docs.python.org/3.10/library/collections.abc.html#collections.abc.MutableMapping

Hope this helps.

**Comment by nepto** [comment]
For anyone who has no idea how to fix it, here is a small patch you can apply:

````
--- /usr/local/lib/python3.11/dist-packages/tornado/httputil.py.ori	2024-11-09 00:38:55.011940657 +0100
+++ /usr/local/lib/python3.11/dist-packages/tornado/httputil.py	2024-11-09 00:38:59.380002273 +0100
@@ -24,6 +24,7 @@
 
 import calendar
 import collections
+from collections.abc import MutableMapping
 import copy
 import datetime
 import email.utils
@@ -103,7 +104,7 @@
 _normalized_headers = _NormalizedHeaderCache(1000)
 
-class HTTPHeaders(collections.MutableMapping):
+class HTTPHeaders(MutableMapping):
     """A dictionary that maintains ``Http-Header-Case`` for all keys.
 
     Supports multiple values per key via a pair of new methods,
 ````

I tested this on `Python/3.11`, and it worked well.

Now my `tornado/4.5.3` and `tailon/1.4.3` run on this Python
